11708 files found
Loading point clouds...
  5%|██████▌                                                                                                                  | 638/11708 [00:05<01:36, 114.33it/s]
Traceback (most recent call last):
  File "/home/aniemcz/gooseReno/.pixi/envs/default/lib/python3.10/multiprocessing/pool.py", line 856, in next
    item = self._items.popleft()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aniemcz/gooseReno/RENO/kit/io.py", line 33, in read_point_clouds
    pcs = list(tqdm(p.imap(read_points, file_path_list), total=len(file_path_list)))
  File "/home/aniemcz/gooseReno/.pixi/envs/default/lib/python3.10/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/home/aniemcz/gooseReno/.pixi/envs/default/lib/python3.10/multiprocessing/pool.py", line 861, in next
    self._cond.wait(timeout)
  File "/home/aniemcz/gooseReno/.pixi/envs/default/lib/python3.10/threading.py", line 320, in wait
    waiter.acquire()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aniemcz/gooseReno/RENO/train.py", line 88, in <module>
    dataset=PCDataset(files, is_pre_quantized=args.is_data_pre_quantized),
  File "/home/aniemcz/gooseReno/RENO/dataset.py", line 7, in __init__
    self.files = io.read_point_clouds(file_path_ls)
  File "/home/aniemcz/gooseReno/RENO/kit/io.py", line 32, in read_point_clouds
    with multiprocessing.Pool(64) as p:
  File "/home/aniemcz/gooseReno/.pixi/envs/default/lib/python3.10/multiprocessing/pool.py", line 739, in __exit__
    self.terminate()
  File "/home/aniemcz/gooseReno/.pixi/envs/default/lib/python3.10/multiprocessing/pool.py", line 657, in terminate
    self._terminate()
  File "/home/aniemcz/gooseReno/.pixi/envs/default/lib/python3.10/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/aniemcz/gooseReno/.pixi/envs/default/lib/python3.10/multiprocessing/pool.py", line 703, in _terminate_pool
    outqueue.put(None)                  # sentinel
  File "/home/aniemcz/gooseReno/.pixi/envs/default/lib/python3.10/multiprocessing/queues.py", line 376, in put
    with self._wlock:
  File "/home/aniemcz/gooseReno/.pixi/envs/default/lib/python3.10/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/aniemcz/gooseReno/.pixi/envs/default/lib/python3.10/multiprocessing/pool.py", line 856, in next
    item = self._items.popleft()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aniemcz/gooseReno/RENO/kit/io.py", line 33, in read_point_clouds
    pcs = list(tqdm(p.imap(read_points, file_path_list), total=len(file_path_list)))
  File "/home/aniemcz/gooseReno/.pixi/envs/default/lib/python3.10/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/home/aniemcz/gooseReno/.pixi/envs/default/lib/python3.10/multiprocessing/pool.py", line 861, in next
    self._cond.wait(timeout)
  File "/home/aniemcz/gooseReno/.pixi/envs/default/lib/python3.10/threading.py", line 320, in wait
    waiter.acquire()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aniemcz/gooseReno/RENO/train.py", line 88, in <module>
    dataset=PCDataset(files, is_pre_quantized=args.is_data_pre_quantized),
  File "/home/aniemcz/gooseReno/RENO/dataset.py", line 7, in __init__
    self.files = io.read_point_clouds(file_path_ls)
  File "/home/aniemcz/gooseReno/RENO/kit/io.py", line 32, in read_point_clouds
    with multiprocessing.Pool(64) as p:
  File "/home/aniemcz/gooseReno/.pixi/envs/default/lib/python3.10/multiprocessing/pool.py", line 739, in __exit__
    self.terminate()
  File "/home/aniemcz/gooseReno/.pixi/envs/default/lib/python3.10/multiprocessing/pool.py", line 657, in terminate
    self._terminate()
  File "/home/aniemcz/gooseReno/.pixi/envs/default/lib/python3.10/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/aniemcz/gooseReno/.pixi/envs/default/lib/python3.10/multiprocessing/pool.py", line 703, in _terminate_pool
    outqueue.put(None)                  # sentinel
  File "/home/aniemcz/gooseReno/.pixi/envs/default/lib/python3.10/multiprocessing/queues.py", line 376, in put
    with self._wlock:
  File "/home/aniemcz/gooseReno/.pixi/envs/default/lib/python3.10/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
